# Site settings
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "TLC Nails"
email: "dcarroll809@gmail.com"
author: "Dan Carroll"
description: Blog site for TLC Nails

# Build settings

sass:
  sass_dir: _sass
  style: compressed

# Social icons
#show_social_icons: true
#github_username: someGithubUser
#twitter_username: someTwitterUser  