# Site settings
title: "TLC Nails"
email: "dcarroll809@gmail.com"
author: "Dan 'Floridan' Carroll"
description: Blog site for TLC Nails
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
permalink: :title/
sass:
  sass_dir: _sass
  style: compressed

# Social icons
#show_social_icons: true
#github_username: someGithubUser
#twitter_username: someTwitterUser  